channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env